version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - '5432:5432'
    env_file:
      - ./postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  webapi:
    build: ./WebAPI/WebAPI
    ports:
      - "5001:5001"   #5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Overrides Dockerfile setting
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapi
    ports:
      - "4000:4000"
  webspa:
    build: ./web-spa
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
       - ./web-spa:/app
       - '/app/node_modules'
volumes:
  postgres-data:
